name: Build and Package

on:
  push:
    branches: 
      - beta
  pull_request:
    branches: 
      - beta
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  VERSION: 'beta 2'

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest
    environment: Auto Build And Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.logT }}

      - name: Pre body
        run: |
          echo -e "更新时间：${{ env.logT }}" >> release.txt
          echo -e "> - 1.同步官方beta 2 最新代码.\n> - 2.修复系统文件权限问题.\n> - 3.采用最新第三方UI编译" >> release.txt
      
      - name: Build Bootstrap
        run: |
          make package
          mv ./packages/Bootstrap.tipa Bootstrap.ipa

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          repo: wwg135/Bootstrap
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: Bootstrap_${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: main
          body_path: release.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
